- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- NOTICE.md
- SECURITY.md
This PR will add all the necessary legal files for the eclipse open source project.
Only the DEPENDENCIES are not yet analyzed, since there is no source code yet. This will follow in separate pull requests
> chore: add FOSS files for eclipse project

- docs/release/trg-4/_category_.json
- docs/release/trg-4/trg-4-1.md
Initial release of TRG 4.01 - Image Tagging
> Add TRG 4.01 - Image Tagging

- package-lock.json
- package.json
Bumped versions for:
- docusaurus → 2.2.0
- husky → 8.0.2
> Bump version 

- docs/release/trg-5/trg-5-6.md
Introduce new TRG 5.06 Application configuration
> chore(doc): add TRG 5.06 - Application Configuration

- src/components/HomePageHeader/index.js
- src/components/NewsTicker/index.js
- src/components/NewsTicker/styles.module.css
NewsTicker component defined in `src/components/NewsTicker` folder and it's been called inside of the HomePageHeader component at `src/components/HomePageHeader`. The result is the next in the home page:
> Add/news-ticker component 

- docs/release/trg-4/trg-4-1.md
- docs/release/trg-4/trg-4-4.md
Signed-off-by: ricogu <yuanxun.gu@sap.com>
> add trg 4.04

- docs/release/trg-3/_category_.json
- docs/release/trg-3/trg-3-1.md
- docs/release/trg-3/trg-3-2.md
New TRG sections are created/moved:
- TRG 3.01 - Supported Versions
- TRG 3.02 - Persist Data
> Docs/add trg 3.01 and 3.02

- docs/release/trg-2/trg-2-4.md
New TRG 2.04 - Leading product repository with description, rules, example and explanation.
> chore: add trg 2.04 leading product repository

- docs/release/trg-5/trg-5-2.md
Signed-off-by: ricogu <yuanxun.gu@sap.com>
> update trg 5-2 history

- src/components/HomePageHeader/index.js
> fix/project name in home page header/banner

- docs/kits/Business Partner Kit/page_adoption-view.md
- src/css/custom.css
This PR solves issue #75, by simply adding the proper styling to the `custom.css` file
> generating method icons next to items in the sidebar navigation

- docusaurus.config.js
> added useful links section with 5 new links items to footer

- docs/release/trg-2/trg-2-3.md
> chore: fix typo in trg-2-03

- docs/release/trg-2/trg-2-3.md
> chore: fix broken link

- docs/release/trg-5/trg-5-2.md
old globbing also matched values.yaml without suffixes
> fix(docs): too greedy file glob

- docs/release.md
- docs/release/trg-5/trg-5-4.md
Broke when moving text from trg-0
> fix link in release.md to trg-0

- docs/kits/Business Partner Kit/page_software-operation-view.md
This PR replace broken external link in the `BusinessPartnerKit/operation-view` page
> Change/ BusinessPartnerKit/page_software-operation-view external link

- docs/kits/Business Partner Kit/page_software-operation-view.md
Content from page updated with raw content from https://github.com/eclipse-tractusx/bpdm/blob/main/INSTALL.md
> change/ BusinessPartnerKit/operation-view page content

- docs/kits/Business Partner Kit/page_adoption-view.mdx
- docs/kits/Business Partner Kit/page_changelog.md
- docs/kits/Business Partner Kit/page_documentation.md
- docs/kits/Business Partner Kit/page_software-operation-view.md
This PR simply add a changelog.md file to `docs/BusinessPartenerKit/`, the front matter of the rest of .md files is been updated to reorder the sidebar navigation as desired
> add/ changelog.md file to BP-Kit

- docs/kits/Business Partner Kit/page_adoption-view.mdx
Links added to `docs/kits/BusinessPartnerKit/page_adoption.view.mdx` file
> add/ content to bp_adoption-view file

- src/components/CarouselComponent/index.js
- utils/galleryKits.js
LInks to `ConnectorKit/adoption-view` from:
- `src/components/CarouselComponent`
- `src/components/KitsGallery`
> Add/links to Connector-Kit 

- docs/release/trg-0/trg-0-helm-test.md
The sample workflow contains an indentation error - this should fix it. :)
> chore(docs): Fix indentation in checkout step

- docs/kits/Data Chain Kit/page_software-operation-view.md
I did some updating and polishing of the Data Chain Kit operation view. I also added missing information that was requested in the hands-on session.
> Polish operation view of Data Chain Kit

- docs/oss/issues.md
add more examples
- added 2 more links as examples for requesting repository changes in our organisation
- give more help / examples or advisory for updating repository within GitLab
- checkout branch
- npm install
- npm start
searched for some examples for change requests for repositories within GitLab with prefix tractus-x
would look like this
> add more examples for gitlab issues

- utils/products.js
@paullatzelsperger and I are the main committers for the EDC product at the moment, therefor I updated the product entry on the community page.
> docs(products): Update committers of EDC product

- docusaurus.config.js
This PR fixes #166 by updating the docusaurus configuration to re-enable an Open API generation.
> fix: open api generation

- blog/2023-05-26-release-3-1-0.md
> add/news release 3.1.0 

- docs/kit-process/graduation-process.md
- sidebars.js
> fix: update id of general worklof in sidebar.js fixes #254

- docs/release/trg-5/trg-5-09.md
- fix helm upgrade step
example workflow should be generic and not reference portal.
> docs(helm-test): fix helm upgrade step

- docs/oss/how-to-contribute.md
Fixing typos in the content of contribution page.
> chore: fix typo in the contribution page

- docs/developer.md
Added initial text to our developer hub intro page.
> feat: add initial intro text to developer hub

- src/components/DeveloperContent/index.js
> fix: broken link to artefacts list

- docs-kits/kits/Digital Twin Kit/Software Development View/page_software-development-view.md
Reverts eclipse-tractusx/eclipse-tractusx.github.io#294
> Revert "docs: Add Examples for AAS-Registration at EDC Management API"

- docs-kits/kits/Business Partner Kit/page_software-operation-view.md
Operational view for BPDM kit updated with correct service names and the changes related to Saas is removed.
Now, Operational view is having steps sync with helm chart deployment steps in BPDM repo. 
Due to limitations of docusaurus and versioning, could not link README.md files from BPDM repo.
> docs(bpdmKit):changes for operation view

- docs/kit-process/processes/update-documentation.md
This PR solves issues #342 and #343 
The necessary and specific changes have been applied according to the raised issues and the resultant UI is as follows:
**Note:** The `@danielmiehle` and `maximilianong` links navigate to their respective `GitHub` profile pages
> Fix(doc)/kit-process-documentation

- docs-kits/kits/Digital Twin Kit/Software Development View/page_software-development-view.md
- docs-kits/kits/Digital Twin Kit/page_adoption-view.md
- docs-kits/kits/Digital Twin Kit/page_changelog.md
- openApi/dt/discovery-finder-openapi.yaml
This PR includes the last fixes after qg4-review. It bumps the version to 1.0.0, reflecting the conditional approval of release management.
> doc: set DT Kit to 1.0.0

- docs-kits/kits/Data Chain Kit/page_adoption-view.md
- fix(adoption_view):[#360] removed incorrect img reference
> fix(adoption_view):[#360] removed incorrect img reference

- docs-kits/kits/Data Chain Kit/page_changelog.md
- sidebarsDocsKits.js
- fix(sidebar):[#360] fixed id in sidebarsDocs
> fix(sidebar):[#360] fixed id in sidebarsDocs

- docs-kits/kits/Business Partner Kit/page_adoption-view.mdx
- docs-kits/kits/Business Partner Kit/page_changelog.md
In this pull request, added CC BY 4.0 License for Adoption View, updated Change Log and updated adaption view considering TRG.
> fix(docs): updated documents for bpdm kit with TRG

- docs-kits/kits/Business Partner Kit/page_adoption-view.mdx
In this pull request, updated standards for BPDM kit on adoption view page. 
Also provided Catena-X Standard Library url under standards section.
> feat(docs): updated standards for BPDM kit

- docs-kits/kits/Quality-Kit/Software Development View/page_software-development-view.md
- docs-kits/kits/Quality-Kit/page_adoption-view.md
Content update
Update text content in development and adoption view.
> updates(docs-kits): update content in development and adoption view

- docusaurus.config.js
Removed duplicate header label from the kits.
> updates(header kits): remove duplicate label

- docs-kits/kits/Data Chain Kit/page_adoption-view.md
- Added CC-BY-4.0 license information to adoption view of Data Chain Kit
> chore(data-chain-kit): Add CC-BY-4.0 License information

- docs/github-checks.mdx
- add the new reference for Release Guideline Checks
fixes: https://github.com/eclipse-tractusx/sig-infra/issues/260
> (chore): modify ressource link for release guideline checks

- docs-kits/kits/Data Chain Kit/page_adoption-view.md
chore(TRI-1302) add first use case esr to adoption view
> chore(TRI-1302) add first use case esr to adoption view

- .tractusx
PR to update .tractusx metadata file with repo category.
> fix: .tractusx metadata file update with repo category

- blog/2023-09-20-community-days.md
just added one link to register to the community days.
> added the link to the registration to the community days

- docs-kits_versioned_docs/version-23.09/kits/Digital Twin Kit/Software Development View/page_software-development-view.md
minor changes on DTR EDC data asset structure. No changes in "next" since entire structure will change significantly in R23-12 anyway.
> chore: DT Kit r23-09 clarification

- docs/release/trg-2/trg-2-4.md
Link is broken ... fixed by this PR
> fix(trg-2-4) broken link reference to trg-5-08

- src/components/CommunityComponent/index.js
make whole image component as clickable rather than just text and icon
> updates: make component clickable

- blog/2023-09-08-release-23.09.md
Fixing the typo from "exiting" to "exciting" in the release news: https://eclipse-tractusx.github.io/blog/new-release-23.09
Closes #409
> fixed a typo

- openApi/dt/discovery-finder-openapi.yaml
When running the project with `npm start` as suggested in the documentation of the README, the auto-generated files aren't up-to-date. This PR fixes it by pushing the updated version. 
FYI: @arnoweiss 
> chore: update autogenerated openApi file

- docusaurus.config.js
label preview to Upcoming kits
> updates: change label 

- docs/tutorials/e2e/inform/onboardingMaterial.md
Added short intro to backend integration for e2e tutorials "inform" section
#453 
> (doc): Completed onboarding information material for e2e tutorial

- docs/tutorials/e2e/inform/onboardingMaterial.md
Adjusted the section according to first review from @SeBuSov 
- updated links according to new Catena-X website
Closes #483 
> doc(tutorials): adjustments of chapter 1 get an Overview after review

- docs/tutorials/e2e/prerequisites/prerequisites.md
This PR is for changes made by @JohannesARENA2036. This PR merges the changes to a feature branch `feat/tutorials`
- Updated bash commands after testung, a couple of sudo added.
> doc(tutorials): adjustments after review

- docs/tutorials/e2e/boost/provideData.md
Adjusted documentation according to first feedback. 
- added an info box for lesson learned in this tutorial
- fixed typos
- rephrazed some sentences to improve readability
Issue #486 
> doc(tutorials): Adjustments of chapter 3 provide data after review

- docs/tutorials/e2e/boost/consumeData.md
Deletetion of "work in progress-note"
> doc(tutorials): Minor adjustments on chapter3/Consume Data

- blog/2023-11-22-release_tutorials.mdx
Change the heading structure in the news entry and add the sty connected section to promote the mailinglist and matrix chat.
> doc(tutorials): publish new tutorial section

- docs/release/trg-7/trg-7-04.md
- modify dash licence plugin information to current released plugin version 
- fix typos
> chore: update DASH license Plugin config + fix typo

- docs-kits/kits/Behaviour Twin RuL Kit/page_adoption-view.md
Remaining Useful Life Kit, Standard section: update links as they are now available in the CX standards library.
> RuL-Kit/Adoption view: update links to published standards

- docs-kits/kits/Data Chain Kit/page_adoption-view.md
- Added IRS use-cases ESS top-down, ESS bottom-up and DIL
> Add IRS use-cases ESS and DIL to Data Chain Kit Adoption View

- docs-kits/kits/Behaviour Twin HI Kit/page_adoption-view.md
- docs-kits/kits/Behaviour Twin HI Kit/page_changelog.md
- docs-kits/kits/Behaviour Twin MDP Kit/page_adoption-view.md
- docs-kits/kits/Behaviour Twin MDP Kit/page_changelog.md
- src/components/DeveloperContent/index.js
Found additional linting issues after original fix and img links.
> fix linting and missing img link issues

- docs-kits/kits/Behaviour Twin HI Kit/page_changelog.md
> updates: version update in Behaviour Twin HI Kit

- docs-kits/kits/Behaviour Twin HI Kit/page_changelog.md
> updates: update release date

- docs-kits/kits/Quality-Kit/page_adoption-view.md
Document Use Case Framework Quality v1 added
Update list of related standards
License notice added
Quality KIT Release 23.12 Adoption View Acceptance Criteria #162
> Quality KIT Release 23.12 Update page_adoption-view.md

- docs-kits/kits/Quality-Kit/Software Development View/page_software-development-view.md
Updated Asset Transfer recommendation
Updated Asset Transfer recommendation
Quality KIT Release 23.12 Development View Acceptance Criteria #163
> Quality KIT Release 23.12 Update page_software-development-view.md

- blog/2024-01-10-open-planning.mdx
Since the meeting will be canceled, it should also be documented.
> doc(blog open planning): document the canceled meeting "open refinement"

- docs/release/trg-4/trg-4-02.md
- docs/release/trg-4/trg-4-05.md
- docs/release/trg-4/trg-4-06.md
PR to update [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02/) content as per https://github.com/eclipse-tractusx/sig-infra/issues/368 .
> docs: update trg-4-02

- DEPENDENCIES
- docs/release/trg-2/trg-2-5.md
- reword the why section and the information why this metafile is important for automation
fixes https://github.com/eclipse-tractusx/sig-infra/issues/371
> docs: reword why section and add current link to the board

- docs/release/trg-1/trg-1-3.md
- add best practice section 
- add example chanagelog
- add link to general Changelog
- reword the why and description
fixes https://github.com/eclipse-tractusx/sig-infra/issues/363
> docs: add Changelog example and best practice section

- DEPENDENCIES
- blog-meeting-minutes/2024-02-02-office-hour.md
- blog-meeting-minutes/authors.yaml
- add meeting minutes
- checked with npm run build / npm run serve
> docs: add last 02022024 office hour meeting minutes

- docs/tutorials/e2e/prerequisites/prerequisites.md
Minor changes - the commands are now displayed in separate code blocks -> easier to copy and execute step by step.
> doc(tutorials): Update prerequisites - make it more readable

- docs/tutorials/e2e/boost/consumeData.md
When we were at the TractusX Community Days, we noticed that the workflow in the tutorial for the Consume Data step was not correct. We have added some steps and extended others. So that it is clear to the users what they have to do to get data.
> fix(tutorials): update consume data flow

- blog-meeting-minutes/2024-02-09-office-hour.md
- blog-meeting-minutes/authors.yaml
PR to add  2024-02-09 Office hour meeting minutes.
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/436
> docs: add office hour meeting minutes 2024-02-09

- docs-kits/kits/Business Partner Kit/page_adoption-view.mdx
In this pull request, we have updated the use case URL and updated the notice for business partner kit.
fix #663  
> Docs(business-partner-kit):use case url updated and notice updated

- community/open-meetings.mdx
Extend the open meeting next week as aligned in the last meeting 
> doc(open-meeting): extend open meeting trace-x on 22.02.2024

- blog-meeting-minutes/2023-12-06-new-open-meeting-blog.md
- add the information where the former blog posts can be found
updates https://github.com/eclipse-tractusx/sig-infra/issues/348
> docs: add blog post folder link

- community/open-meetings.mdx
- static/meetings/osp-feature-demo.ics
This PR adds a new open meeting to our [open meetings page](https://eclipse-tractusx.github.io/community/open-meetings).
> doc(open meetings): add new open meeting for osp feature demo

- docs-kits/kits/DCM Kit/page_adoption-view.md
- docs-kits/kits/DCM Kit/page_changelog.md
- docs-kits/kits/DCM Kit/page_development-view.md
Please describe your PR: 
- What does this PR introduce? Fix Issue #694 
- Does it fix a bug? Fix Linter Findings
- Does it add a new feature? No
- Is it enhancing documentation? No
Closes #694 
> (fix) Fix Issue #694: [DCM KIT] Fix Markdown Linting Issues

- blog-meeting-minutes/2024-02-16-office-hour.md
Adding the office hour meeting minutes for 2024-02-16
> docs(community): add office hour meeting minutes feb 16

- blog-meeting-minutes/2024-02-23-office-hour.md
Adding the office hour meeting minutest for 23 Feb 2024
> docs(open-meetings): add 23 feb office hour

- community/open-meetings.mdx
Add matrix chat rooms or irs and trace-X to open meetings as addtional links 
> chore(meetings): add matrix chats as additional information

- docs/release/trg-3/trg-3-2.md
PR to add information about Persistent Volume reclaim policy to TRG 3.02.
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/372
> docs: enhance trg 3 02

- blog/2024-05-16-community-days.mdx
Just a small additional information -> add timing information to the blog entry requested by arena2036
> doc(blog): Adapt detailed planning information

- community/open-meetings.mdx
Change meeting schedule of Trace-X Open Meeting 
> Change meeting schedule from 2:05 to 3:05 pm   open-meetings.mdx

- docs-kits/kits/Digital Twin Kit/Software Development View/page_software-development-view.md
Table on Versioning: more text added
+
typos, formatting, adding text for clarity
> [DT KIT] Versioning updated + minor changes

- docs-kits/kits/ESS-Kit/changelog.md
- docs-kits/kits/ESS-Kit/page_adoption-view.md
- docs-kits/kits/ESS-Kit/page_documentation.md
Just add the changelog to the ess-kit and change the order for the files
> doc(ess-kit): add changelog to kit

- community/open-meetings.mdx
Provide link to open-meetings agenda
-->
> Provide link to open-meetings agenda

- docs-kits/kits/Industry Core Kit/page_architecture-view.mdx
- docs-kits/kits/Traceability Kit/page_architecture-view.mdx
This PR fixes two broken links in the Traceability and Industry Core KIT.
> docs(trace-ic): fix broken links

- docs-kits/kits/Data Chain Kit/page_adoption-view.md
- docs-kits/kits/Data Chain Kit/page_changelog.md
- docs-kits/kits/Data Chain Kit/page_software-operation-view.md
- openApi/dt/discovery-finder-openapi.yaml
update local deployment description for irs for version 4.5.2
> chore(local): update local deployment description for irs

- docs/release/trg-5/trg-5-07.md
- align version in example to current version
> chore: postgresql example to version 12.x.x

- blog-meeting-minutes/2024-03-15-office-hour.md
- add office hour from last friday
fixes https://github.com/eclipse-tractusx/sig-infra/issues/456
@AngelikaWittek Is the wording ok for you?
@stephanbcbauer Do you maybe want to add more or ok for you(updates from the Release Day)?
> docs: add meeting minutes office hour from 15032024

- utils/products.js
update and add product info for portal and policy-hub
> chore: update and add product info for portal and policy-hub

- blog/2024-04-10-open-planning-r24.08.mdx
This PR adapts the issue filter for the PQR domain
> doc(open planning): adapt issue filter

- NOTICE.md
- docusaurus.config.js
Updated website footer according to the changes in the project handbook, cleaned up links.
Website was build locally, no new linter warnings.
> Updated and cleaned up footer

- docs/release/trg-0/trg-9-01.md
- documentation/kit-artifacts.md
- documentation/kit-getting-started.md
- documentation/kit-maturity-levels.md
- docusaurus.config.js
- sidebarsDocumentation.js
- utils/carouselKitdeepdive.js
In this pull request, we have introduced a new folder named "documentation". Additionally, we have established a link from the 'kit creation' button directly to this folder.
> feat(documentation):new folder created

- blog-meeting-minutes/2024-04-12-community-hour.md
as discussed renamed "tractus-x-office-hour" to "community-office-hour"
> chore: add community office hour 20240415

- blog-meeting-minutes/2024-04-12-community-hour.md
This PR aligns date and tagging of this meeting minutes, which were "stuck" in a parallel PR during the renaming
> Chore: finalizing rename of meeting minutes

- docs-kits/kits/Data Chain Kit/Software Development View/Job Api/irs-api.info.mdx
> Feat fix url to SwaggerUI

- blog-meeting-minutes/2024-04-19-office-hour.md
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/480
> docs: add office hour news 24-04-19

- blog-meeting-minutes/2024-04-12-committer-meeting.md
- blog-meeting-minutes/authors.yaml
Meeting minutes for the committer meeting
> doc(meeting minutes): add committer meeting minutes

- docs/release/trg-8/trg-8-01.md
- docs/release/trg-8/trg-8-02.md
- docs/release/trg-8/trg-8-03.md
- docs/release/trg-8/trg-8-04.md
history of TRG 8.1 was not updated properly.
Also fixed the history ordering of all other TRG 8ths
> fix post history and order for trg 8*

- src/components/AboutUsCard/styles.module.css
- src/components/AboutUsHeader/styles.module.css
- src/components/CommunityComponent/styles.module.css
- src/components/DeepdiveHeader/styles.module.css
- src/components/HomePageHeader/styles.module.css
- src/components/KitsGallery/styles.module.css
- src/components/KitsGalleryMDX/styles.module.css
- src/components/KitsGalleryWithFilters/styles.module.css
- src/components/RoleBasedEnrtyComponent/styles.module.css
- src/css/custom.css
- src/pages/Kits/index.js
Align the components and page width based on the browser size.
> fix: align the components in the page based on the browser width

- docs/release/trg-5/trg-5-05.md
Use empty slice to be albe to create ingress with tls disabled.
> docs: adjust trg 5 05 ingress example

- CONTRIBUTING.md
- LICENSE_non-code
- NOTICE.md
Adopt changes to license and legal documentation (TRG-7), resolves #913.
> chore: change license and legal documentation

- README.md
PRs often fail the pipeline because of the DEPENDENCIES file and the dash licence tool. This adds documentation how to avoid that.
> docs(README): explain dash

- community/open-meetings.mdx
add open meeting for umbrella helm chart to facilitate participation from the entire TX community
> docs: add open meeting for umbrella helm chart

- docs/release/trg-8/trg-8-04.md
The modification in the workflow ensures that the SARIF report generated by Trivy only includes vulnerabilities with the specified severity levels ("CRITICAL" and "HIGH" in this case). The build fails if any such vulnerabilities are found, prompting immediate action to resolve them
> docs: Update trg-8-04.md

- docs-kits/kits/ESS-Kit/changelog.md
- docs-kits/kits/ESS-Kit/page_adoption-view.md
- docs-kits/kits/ESS-Kit/page_documentation.md
Update documentation for ESS kit for release 24.8
see also https://github.com/eclipse-tractusx/sig-release/issues/638
> doc: ESS kit update24.8

- docs-kits/kits/Circularity_KIT/page-adoption-view.md
- docs-kits/kits/Circularity_KIT/page_changelog.md
this pull request adds the informational requirements for the end of live data parameters to enable remanufacturing and recycle use cases
Fixes https://github.com/eclipse-tractusx/sig-release/issues/632
> doc(circularity kit): add informational requirements at end of life

- docs/dev_faq.md
- docs/dev_links.md
- docs/getting-started.md
- docs/oss/issues.md
Clean Up System-Team Links on Webpage
> chore: update and cleanup system-team links on webpage

- docs-kits/kits/DCM-Kit/onboarding.md
This PR contains DCM-Kit content for release 24.08.
The following Issues are addressed: 
|Issue ID|Name|Structure|Content|
|--|--|--|--|
|[587](https://github.com/eclipse-tractusx/sig-release/issues/587)|[DCM-KIT] Onboarding for DCM Access ||X|
The structure for the Onboarding page is pulled via https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/981
(https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/981 AND https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/984 AND https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/985) REPLACE https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/969 
> [DCM-KIT] Onboarding for DCM Access #587

- docs-kits/kits/Data Chain Kit/page_software-operation-view.md
- update data chain kit operation view to latest IRS version https://github.com/eclipse-tractusx/item-relationship-service/issues/823
> chore: update data chain kit operation view to latest irs version

- docusaurus.config.js
Fix DCM links due to structural changes
Please describe your PR: 
- What does this PR introduce? Fix DCM links to correct landing page on Eclipse Tractus-X
- Does it fix a bug? No
- Does it add a new feature? No
- Is it enhancing documentation? No
> Fix DCM links due to structural changes

- docs-kits/kits/Data Chain Kit/page_adoption-view.md
update copyright notice to current year 2024
> update copyright notice to current year

- .github/workflows/trufflehog.yml
As mandatory in this issue #1035 I have added the workflow to this repo.
> feat: added the trufflehog workflow

- blog-meeting-minutes/2024-10-18-community-hour.md
- blog-meeting-minutes/authors.yaml
Minutes of the office hour on Oct., 18th 2024
> Minutes office hours Oct. 18th

- blog/2024-12-05-community-days.mdx
This PR add the info to download the agenda, because the pictures are really small ;)
> docs(community days): add info to download the detailed agenda

- blog-meeting-minutes/2024-11-08-community-hour.md
> docs: noted down 2021-11-08 community office hour

- docs-kits_versioned_docs/version-24.08/kits/Industry Core Kit/Software Development View/page_digital-twins.mdx
> Change version of SerialPart from 1.0.1 to 3.0.0

- docs-kits/kits/Industry Core Kit/Software Development View/page_digital-twins.mdx
> Updateversion of SerialParts from 1.0.1 to 3.0.0 page_digital-twins.mdx

- blog-meeting-minutes/2024-10-11-community-hour.md
- blog-meeting-minutes/authors.yaml
This PR adds the minutes of the Office Hour on 11.10.2024 and a new author in the author.yaml file.
> docs(open meetings):  add protocol for 2024-10-11

- community/open-meetings.mdx
This PR adds a new open meeting for BPDM to our [open meetings](https://eclipse-tractusx.github.io/community/open-meetings/) page.
> doc(open meetings): added open meeting for bpdm

- README.md
- community/open-meetings.mdx
add open meeting for portal r2412 and fix typos
> docs: add open meeting for portal r2412 and fix typos

- community/open-meetings.mdx
remove release demo, prolong open meeting
> docs(portal): remove release demo, prolong open meeting

- blog/2024-12-16-kit-icons-update.md
> fixed writung og kit

- community/sigs/05_sig_architecture.md
Added the new `sig-architecture` repository to the webpage.
> feat: added sig-architecture to the webpage

- blog/2025-02-19-release-planning-R25.06.mdx
- community/open-meetings.mdx
This PR adds the different teams sessions to the open meeting agenda.
> docs(open meetings): add teams sessions to agenda for refinement day 1

- DEPENDENCIES
- docs-kits/kits/Traceability Kit/Software Development View/part_aspect-models.mdx
- docs-kits/kits/Traceability Kit/page_changelog.mdx
This PR fixes some broken tables in the Traceability KIT.
Fixes #1135 
> docs(trace): fix broken tables (#1135)

- docs-kits/kits/PCF Exchange Kit/Software Development View/page_software-development-view.md
- docs-kits/kits/PCF Exchange Kit/page_adoption-view.md
content update on PCF kit development and adoption view
> fix: content update on PCF kit development and adoption view

- docs/tutorials/e2e/prerequisites/prerequisites.md
- ave -> have
- admonitions
Fixed typo and admonitions
> fix: typos

- utils/products.js
I have added the industry core hub and tractus-x sdk products and committers.
> feat: added Industry Core Hub and Tractus-X SDK

- docs-kits/kits/Quality-Kit/page_adoption-view.md
- docs-kits/kits/Quality-Kit/page_changelog.md
- docs-kits/kits/Quality-Kit/page_software-development-view.md
- docs-kits/kits/Quality-Kit/page_software-operation-view.md
- relates to https://github.com/eclipse-tractusx/sig-release/issues/1218
- Updates the structure of the KIT to be compliant with the requirements from T-X
> DDQM - updated kit structure

- blog-meeting-minutes/2025-03-21-community-hour.md
> chore: add minutes for contributor meeting

- docs-kits/kits/demand-and-capacity-management-kit/development-view/api-capacity-group.md
- docs-kits/kits/demand-and-capacity-management-kit/development-view/api-material-demand.md
- docs-kits_versioned_docs/version-25.03/kits/demand-and-capacity-management-kit/development-view/api-capacity-group.md
- docs-kits_versioned_docs/version-25.03/kits/demand-and-capacity-management-kit/development-view/api-material-demand.md
The description of WeekBasedMaterialDemand and WeekBasedCapacityGroup API flows are reversed. This PR fixes this.
#1188
> Reverse Flow in DCM documentation

- docusaurus.config.js
- utils/kitsGallery.js
- fixes broken links to osim kit
> (bug) fix osim links

- community/open-meetings.mdx
Portal Open Meeting:
- change timeslot to Tuesday morning
- more concrete agenda
- change responsible
- add feature board
> docs(portal-meeting): change timeslot and agenda

- blog/2025-04-25-docusaurus-upgrade.md
- utils/newsTitles.js
This PR adds the information about our website update
> docs(blog): add news blog for upgrade

- blog/2025-03-20-release-planning-R25.09.mdx
Detailed agenda has been added to the news blog for the Open Planning.
> docs(open planning): adapt open planning information

- docs/website-guidelines/wiki.md
Typo issues fixed in wiki file
#1266 
> fix: typo issues

- blog-meeting-minutes/2025-05-16-community-hour.md
Add minutes for community meeting on 2025-05-16
> Minutes for community hour 2025-05-16

- community/open-meetings.mdx
change contact for umbrella sync from @evegufy to @mgarciaLKS 
> docs(community meetings): change contact for umbrella sync

- blog-meeting-minutes/2025-07-04-community-hour.md
added protocol for 2025-07-04.
> docs: add protocol office hour 2025-07-04

- blog-meeting-minutes/2025-08-08-community-hour.md
> docs(office-hour): add protocoll for office hour

- .tractusx
- openApi/supply-chain-disruption-notification/kit_supply-chain-disruption-notification-demandAndCapacityNotification-openAPI_2.0.0.yaml
solves #1319 
Note: Currently none of the openApi specifications does have a license header.
> feat(SCDN-KIT): add openApi specification
