docs/release/trg-2/assets/AUTHORS.txt
docs/release/trg-2/assets/CODE_OF_CONDUCT.txt
docs/release/trg-2/assets/CONTRIBUTING.txt
docs/release/trg-2/assets/LICENSE.txt
docs/release/trg-2/assets/NOTICE.txt
docs/release/trg-2/assets/SECURITY.txt
docs/release/trg-2/trg-2-3.md

Add more details to repository structure requirements for Eclipse-Tractusx repositories to be OSS/Eclipse compliant.

docs: add OSS requirements to TRG 2.03

---

docs/release/trg-5/trg-5-7.md
package-lock.json

- Chart Dependencies TRG added
- A table with the required versions are at the bottom, currently only postgresql is defined
How to test:
1. Pull code
2. From the root of the git repo run: `npm install` (at least nodejs v16 is required)
3. Run `npm start`
4. Open in browser, navigate to `Documentation/Release Guidelines/TRG 5 - Helm/TRG 5.07 - Chart Dependencies` section

docs(add): new TRG 5.07

---

src/css/custom.css

The dark theme colours are substituted according to the planning to match the desired design. The background colour of the footer & navigation is set to black for the moment, future changes in the background styles could be added.

dark theme palette overwritten

---

.gitignore
docs/release/trg-4/trg-4-2.md

This is an initial draft for Tractus-X release guidelines on docker/container base images

Add initial release guidelines on docker base images

---

docs/release/trg-0.md

Those are no longer just drafts.

Remove 'draft' warning on trg index

---

docs/release/trg-5/trg-5-8.md

New TRG 5.08 - Product Helm Chart with description, rules and explanation. Leading product repository leads to a not existing page as it hasn't been created yet.

chore: add trg 5.08 product helm chart

---

docusaurus.config.js

@SebastianBezold @danielmiehle here I am uncommenting all navigation items from the `NavBar`, the KITs link is navigating to /docs/kits (as the original version) and the Developer link is sticking to the Figma design and navigating to /developer.

uncommenting navigation items

---

docs/github-checks.mdx
sidebars.js

- Central Github Checks page
- Embedded `https://tractusx-gh-org-checks.core.demo.catena-x.net/`
Remarks: 
- Url currently unreachable until [corresponding PR](https://github.com/catenax-ng/k8s-cluster-stack/pull/296) is approved and merged
- Double scrollbar will be addressed in a future gh-org-checks release, not from this application

feat: add eclipse gh org checks

---

docusaurus.config.js

This PR includes more content to the footer of the web page, where the section/column `Eclipse Foundation` is added with its respective links to external pages, the UI displays:  
This PR fixed issue #60

add footer content in Eclipse Foundation section

---

src/components/AboutUsCard/index.js
src/components/AboutUsContent/index.js
src/components/AboutUsHeader/index.js
src/components/CarouselComponent/index.js
src/components/DeveloperContent/index.js
src/components/DeveloperHeader/index.js
src/components/FAQsComponent/index.js
src/components/HomePageHeader/index.js
src/components/KitsCard/index.js
src/components/KitsGallery/index.js
src/components/NewsTicker/index.js
src/pages/AboutUs/index.js
src/pages/Developer/index.js
src/pages/index.js

This PR solves issue #74 
The next header:
Has been added to the `React` components and pages in:
- `.src/components/*`
-  `./src/pages/AboutUs`
- `./src/pages/Developer`

Add Copyright Header to components

---

NOTICE.md

This PR modify the content of the `NOTICE.md` file, ## Trademarks section:
**Eclipse Tractus-X is a trademark of the Eclipse Foundation. Eclipse, and the Eclipse Logo are registered trademarks of the Eclipse Foundation.**
@SebastianBezold @danielmiehle

NOTICE.md trademark content added to comply legal requirements

---

docs/release/trg-1/trg-1-3.md

Be more precise that keep a changelog is mandatory for `CHANGELOG.md` file content.

chore: reference Keep A Changelog and make it mandatory

---

src/components/CarouselComponent/index.js
utils/carouselKits.js

This PR doesn't change the behaviour of the `CarouselComponent`, it is an improvement of the code to make easier its maintaining and most important is allowing to modify from a `JSON` type file (`utils/carouselKits.js`) the content of the cards that are wanted to be displayed. At the moment simple images inside a `Link` that navigate to `docs` folder of each.

change/ refactor CarouselComponent

---

docs/release/trg-2/trg-2-2.md

We still had the workflow for catena-x written which is wrong.
Small hint on using the dev mailing list and the help desk

align trg 2.02 with eclipse workflow

---

.markdownlint.yaml

This PR adds an exception to the markdown linter to allow, e.g., line breaks in tables.
Closes #178

fix(docs): allow HTML in markdown files

---

docs/release/trg-2/trg-2-5.md

- TRG 2.05 should no longer be marked as "prerelease"
- fixed 2 typos

docs: enact TRG 2.05 + fixed typos

---

docs/release/trg-5/trg-5-02.md

Typo corrected, especially for file name. Also added `.helmignore` to example list and enhanced on license/copyright header.

chore: fix typos licence → license

---

docs/release/trg-4/trg-4-01.md

As _TRG 4.05 - Container registries_ got introduced, we had 2 different workflow examples in our TRGs for container image tagging. This is to align the workflows again.

chore: TRG 4.01 - update example workflow

---

docs/release/trg-0/trg-0.md
docs/release/trg-5/trg-5-09.md

- provide example to enable workflow for testing of different k8s versions and helm upgrade via workflow dispatch
- enable chart-testing (install) and helm upgrade steps to not be skipped on workflow dispatch (adjusted if statement)
- upgrade container-tools/kind-action as default version (v0.17.0) uses node image v1.21.1 and doesn't work with more recent node image versions
- replace deprecated set-output command
- update changelog

docs(trg-helm): improve helm test workflow

---

src/components/HomePageHeader/styles.module.css
src/components/NewsTicker/styles.module.css

---
name: Fix/Home-Page-Header BG dimensions
about: 'background position adjusted at 600px width and padding-top decrease, both changes occurred in the home page header component'
title: 'fix|Home-Page-Header BG dimensions'
---
This simple PR improves the UI of the `HomePageHeader` component when it displayed in small screen devices, it contains 2 minor changes that affects the position of the BG and the padding-top of the banner when displayed in devices =< 600px.
N/A

Fix/Home-Page-Header BG dimensions

---

docs/release/trg-0/trg-3-2.md
docs/release/trg-0/trg-5-02.md
docs/release/trg-0/trg-5-11.md

Consolidated update of 3 TRGs:
- TRG 5.02 - made templates/NOTES.txt file as optional for the Helm Chart structure, aligning with [Helm documentation](https://helm.sh/docs/topics/charts/)
- TRG-3.2 & TRG 5.11 typo fixes
Updates https://github.com/eclipse-tractusx/sig-infra/issues/93
- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to- …

fix: TRG update

---

docs/release/trg-0/trg-7-01.md

New SECURITY.md vulnerability "policy".
First report vulnerabilities via a GitHub security advisory and then to the Eclipse security dashboard. This is agreed with the Eclipse security team.
The new SECURITY.md is shown in code below.

docs: Create trg-7-01.md

---

docs/oss/how-to-contribute.md

The link semantic in the related md file is not correct. [dev mailinglist]((https://www.eclipse.org/projects/handbook/#resources-dev-list)) should be [dev mailinglist](https://www.eclipse.org/projects/handbook/#resources-dev-list)
Link wasn't working
Closes #396

docs(how to contribute): adapted wrong link syntax

---

docusaurus.config.js
package-lock.json
package.json

The goal is to eliminate working results which are not compliant with the openSource strategies.
The release cycle information is currently "just" a png which should be replaced by a diagramm as code
-> Please see issue #352 therefore the mermaid functionality is needed
There will be another PR which replaces the picture like it is mentioned in the issue #352 
The theme could also be adapted if necessary, but this is not part of this PR.

docs(general): activate mermaid functionality in markdown

---

src/pages/release-information.md

The goal is to eliminate working results which are not compliant with the openSource strategies.
The release cycle information is currently "just" a png which should be replaced by a diagramm as code
-> Please see issue #352 therefore the mermaid functionality is needed

Releaseinformation adapted

---

docs-kits/kits/knowledge-agents/adoption-view/intro.md
docs-kits/kits/knowledge-agents/development-view/Arc42.md
docs-kits/kits/knowledge-agents/development-view/architecture.md
docs-kits/kits/knowledge-agents/development-view/modules.md
docs-kits/kits/knowledge-agents/operation-view/deployment.md
docs-kits/kits/knowledge-agents/page_changelog.md

The used @static links to the Kit Icon works in docusaurus start but not docusaurus build.
see https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/actions/runs/6354301937/job/17260541967

fix(agents-kit): do not use @static reference to images

---

docs-kits/kits/knowledge-agents/adoption-view/intro.md
docs-kits/kits/knowledge-agents/development-view/Arc42.md
docs-kits/kits/knowledge-agents/development-view/architecture.md
docs-kits/kits/knowledge-agents/operation-view/deployment.md
docs-kits/kits/knowledge-agents/page_changelog.md

Currently, tractusx website does not build due to broken icon links. This was supposed an absolute versus relative linking issue, but indeed it was a case sensitivity in the icon image name.
did build again locally on MacOs, but that show to be case insensitive before. Final check can only be done by merging IMHO.

fix(agents-kit): Icon links are case-sensitive.

---

docs/release/trg-0/trg-0.md
docs/release/trg-4/trg-4-02.md
docs/release/trg-4/trg-4-06.md

add alpine linux to list of container base images
base image for init container needed
fixes https://github.com/eclipse-tractusx/sig-infra/issues/259

docs(trg4.02/06): add alpine linux to list of container base images

---

blog/2023-10-26-open-planning.mdx

Update Blog Post as an invitation for the open source planning day(s) with detailed information and agenda and teamslinks

Blog Post Update for Open Planning Days

---

docs/release/trg-0/trg-1-4.md

- add new trg as draft to alignment on diagrams as code
- enhancing required documentation for our product repositories
updates https://github.com/eclipse-tractusx/sig-infra/issues/87
- checkout pr branch
- npm install (optional)
- npm start 
- verfiy changes

chore: add drawing as code trg as draft

---

docs/tutorials.md

Generic introduction to tutorials - the page somehow needs to be there, because it's where you land when you click on "tutorials" on the top bar. A detailled description of the e2e tutorial is given, so I think we don't need to elaborate extensively on what generic tutorials are - every developer knows that. And Catena-X isn't really special here. 
#449 

Added generic tutorial description

---

docs/release/trg-2/trg-2-5.md

This PR simplifies the descriptions for [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) and 
adds a link to the `.tractusx` metadata file docs to always keep the description up-to-date.
Because this could lead to someone missing updates to the metadata structure, a complete and up-to-date example of a metadata file is also added at the end.
relevant to eclipse-tractusx/sig-infra#309

docs(trg): add a reference to the metadata docs in TRG 2.05

---

docs/release/trg-4/trg-4-02.md

This PR tries to add more background info on the base image alignment process.
It should make the prerequisites for being added to the aligned base image list clearer.
There is also a hint about non-published images and how to skip the automated base image check
relevant to eclipse-tractusx/sig-infra#309

docs(trg): enhance description for base image alignment

---

docs/release/trg-4/trg-4-06.md

This PR combines a split example of the notice for docker images section of the README.
This should make it easier to use and follow

docs(trg): combine notice example to one in TRG 4.06

---

docs/release/trg-5/trg-5-09.md
docs/release/trg-5/trg-5-10.md
docs/release/trg-5/trg-5-11.md

docs: TRG 5.09, 5.10, 5.11 title to lose PRERELEASE postfix and other content cleanup

---

docs/tutorials/e2e/boost/consumeData.md

Adjusted the consume data part according to first feedback
- Added webhook.site as potential backend for testing data transfer
- Fixed 2 typos
- Changed contract ID placeholder with correct contract ID for the tutorial
Closes #487 

doc(tutorials): adjustments of chapter 3 consume data after review

---

docs/tutorials/e2e/boost/restrictData.md

Improved readability 
- partly rephrazed existing content
- added info box for clarification
Issue #488 

doc(tutorials): Adjustments of chapter 3/Restricting users after review

---

docs/oss/getting-started.md

- add link to our contributpr issue template
- add link to our committer list
- update reference documentation
fixes #492 
> INFO Vetted license information was found for all content. No further investigation is required.

chore: add link to our issue template and link the committer list

---

docs-kits/kits/Traceability Kit/page_software-operation-view.md

Fix wrong link to traceability-foss backend.

docs: Traceability-Kit Operation View - fix link to trace-x backend

---

docs-kits/kits/Behaviour Twin MDP Kit/page_adoption-view.md
docs-kits/kits/Behaviour Twin MDP Kit/page_changelog.md

Github action missed the broken image links. This broke the build.
Quick fix by removing the reference.

fix broken image references

---

docs-kits/kits/PURIS Kit/page_adoption-view.md
docs-kits/kits/PURIS Kit/page_changelog.md
sidebarsDocsKits.js
utils/resiliencyItems.js

The PURIS team wants to update the content of their current preview Kit in anticipation of a `24.05` release.
The goal of this Pull Request is to:
- Update content of the Kit
- Fix broken linking on "Upcoming Kits" page for the resiliency domain page to the PURIS Kit page
- Introduce current folder structure proposed by the wiki/tutorials

feat: PURIS Kit Preview Refresh

---

DEPENDENCIES
docs/release/trg-1/trg-1-4.md

Please describe your PR: 
- moved Draft TRG into correct folder
- switch the TRG into active state for next release
updates https://github.com/eclipse-tractusx/sig-infra/issues/87

docs: move active TRG 1-4 into correct folder

---

docs/release/trg-5/trg-5-09.md

This PR removes the explicit definition of the to be installed helm version by the setup-helm action: Since the Action installs the latest stable version of helm by default anyways.

chore(trg5.09): update workflow example to always use latest stable version of helm

---

utils/kitsGallery.js

The link to the traceability kit on the developer page is broken. This PR fixes the bug by replacing the link.

fix(trace): replace broken link to the traceability kit

---

src/components/AboutUsCard/index.js

Fixed two small typos in prominent https://eclipse-tractusx.github.io/ start page
```diff
- is not-for-profit corporation
+ is a not-for-profit corporation
- that it supported
+ that is supported
```
- [✅] DEPENDENCIES are up-to-date. 
- [✅] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

(doc) About: two small typos

---

DEPENDENCIES
docs/release/trg-1/trg-1-1.md

- add more specifc examples
- add link to https://www.makeareadme.com/
- add link to badges https://github.com/badges/shields/blob/master/README.md
- add description of the importance of the `README.md`
fixes https://github.com/eclipse-tractusx/sig-infra/issues/359

docs(trg1.01): add more detailed information about importance of the readme file

---

docs/release/trg-2/trg-2-3.md

PR to update [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3/) content as per https://github.com/eclipse-tractusx/sig-infra/issues/365.

docs: TRG 2.03 update

---

community/open-meetings.mdx

To follow the open source startegies, we want to publish/communicate all our open meetings. In this case the open planning meeting.

doc(open meetings): add new open planning meeting

---

docs/release/trg-0/trg-2-6.md

PR to introduce new TRG for Dependabot. It's a GitHub feature which supports security and versions' updates automation. 
Idea behind the TRG creation is to help the project keep up to date in best, optimal effort wise way.
Proposing to park it as next item in the GIT section, any suggestions for better place always welcomed.
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/150

docs: new Dependabot TRG

---

docs/release/trg-4/trg-4-03.md

Fixes https://github.com/eclipse-tractusx/sig-infra/issues/369
Adjusted the user ids in the Pod template and added a recommendation section to look for user id created in the base image.
----
I would consider adding more fields as described in the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod) to further enhance security like `runAsGroup`, `fsGroup` and also dropping capabilities. I would welcome some suggestions here.

docs: adjust trg 4.03 on userid

---

community/open-meetings.mdx

Fix broken link in community open meetings section.
closes #619

fix: reference static content correctly

---

docs/tutorials/e2e/boost/provideData.md
docs/tutorials/e2e/connect/deployComponents.md

We were able to gather many impressions at the first TractusX Community Days. This also resulted in some suggestions for improvement.
With this PR we want to integrate the following suggestions.
- Executable commands should be in separate lines so that they can be easily copied on the website
- jq should be appended to the end of the whole reuqest as in MXD, this improves readability
Closes #564 
Closes #562 
Closes #548
Closes #560 

fix(tutorials): Update API health check commands and add JSON parsing with jq

---

docs/tutorials/e2e/connect/deployComponents.md

Removing the whitespace after the backslash allows the user to copy and paste the command to the console without the further modifications.
- [ X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

Simplify copy and pasting commands.

---

docs/release/trg-5/trg-5-08.md
docs/release/trg-5/trg-5-09.md

- fix markdown reference with the full filename within the link, like example in [TRG 5-11](https://raw.githubusercontent.com/eclipse-tractusx/eclipse-tractusx.github.io/main/docs/release/trg-5/trg-5-11.md)
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/blob/0ba0454a402d4c8c3ccf727c9ce0151efaeb8af5/docs/release/trg-5/trg-5-11.md?plain=1#L18
- fix typo `GitHub`
fixes https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/219
was validated with 
- `npm run build`
- `npm run serve`

fix: reference links for helm test TRG 5-09 within TRG 5-08

---

package.json

This PR pins the version of "@docusaurus/plugin-client-redirects" to exactly match the core docsaurus version.
This is a mandatory requirement for all `@docusarus` libraries

fix: pin client redirect plugin version to stay compatible with docusaurus

---

docs-kits_versioned_docs/version-23.12/kits/Business Partner Kit/Software Development View/page_software-development-view.md
docs-kits_versioned_docs/version-3.1.0/kits/Business Partner Kit/page_software-operation-view.md

References/links for Business parter kit were broken for old versions, and in this pull request we have fixed them.
This pull request fixes, warning mentioned in  #639 to tag @SujitMBRDI
The issue #639 cannot be closed by this PR because there are more warnings from other kits.

fix(business partner kit): fixed markdown linter warnings for kit

---

community/open-meetings.mdx
static/meetings/coordination-feature-development-trace-x.ics

This Prs add a new open meeting for trace-x to our [open meeting](https://eclipse-tractusx.github.io/community/open-meetings) page => There will be a new entry, which looks like:
Additional there will be a downloadable ics file which looks like after import:
_Unfortunately, we lose the formatting in the file_
Since we want to provide regular meetings and one-time meetings ... this PR also add the headlines for these categories.

doc(open meetings): add new open meeting for trace-x

---

docs-kits_versioned_docs/version-23.09/kits/tractusx-edc/docs/README.md
docs-kits_versioned_docs/version-23.09/kits/tractusx-edc/docs/kit/operation-view/page08_api.md
docs-kits_versioned_docs/version-23.09/kits/tractusx-edc/docs/samples/Transfer Data.md
docs-kits_versioned_docs/version-23.12/kits/tractusx-edc/docs/README.md
docs-kits_versioned_docs/version-23.12/kits/tractusx-edc/docs/kit/operation-view/page08_api.md
docs-kits_versioned_docs/version-23.12/kits/tractusx-edc/docs/samples/Transfer Data.md
docs-kits_versioned_docs/version-3.1.0/kits/tractusx-edc/docs/kit/operation-view/page08_api.md
docs-kits_versioned_docs/version-3.1.0/kits/tractusx-edc/docs/samples/Local TXDC Setup.md
docs-kits_versioned_docs/version-3.1.0/kits/tractusx-edc/docs/samples/Transfer Data.md
docs-kits_versioned_docs/version-3.1.0/kits/tractusx-edc/edc-tests/cucumber/README.md

Some links (references in the documentation) are broken, and this PR fixes them. The errors were mentioned in #639 
This PR fixes the errors related to the tags @stephanbcbauer and @stefan-ettl 
The issue #639 cannot be closed by this PR because there are more errors from other kits.

fix(connector kit): fix markdown linter errors for connector kit

---

docs/release/trg-4/trg-4-06.md

This PR is a follow up to a [discussion on our mailing list](https://www.eclipse.org/lists/tractusx-dev/msg00306.html).
The discussion is about making a dedicated "Notice for Docker image" mandatory and no longer allow it to be a section in the top-level `README.md`.
So far, there has only been feedback pro change.
TL;DR from the discussion:
- Moving to a dedicated file is not a lot of work
- Can be used to better address target audience
- There is a character limit for DockerHub descriptions, which might cut off the mandatory notice section at the end of long repository README.md files
Fixes eclipse-tractusx/sig-infra#360

docs(trg): make dedicated container image notice mandatory

---

docs/tutorials/e2e/prerequisites/prerequisites.md

Added info for port 8080, correction of the shell command for generating the hashicorp key, some minor additions.
Closes #577 

fix(tutorials): Update prerequisites.md - minor changes

---

docs-kits/kits/Modular Production Kit/page_adoption-view.md
docs-kits_versioned_docs/version-23.12/kits/Modular Production Kit/page_adoption-view.md

Clarification of copyright notice in the Modular Production KIT. The current release states 
> `Fraunhofer Institute of Optronics, System Technology and Image Exploitation (IOSB)`
where it should have been 
> `Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer IWU & Fraunhofer IOSB & Fraunhofer IPA)`
@wehrstedt-jan 
@danielmiehle @maximilianong 

fix: copyright clarification for modular production KIT

---

.github/workflows/dash.yaml

This PR adds a PR check, that runs [eclipse dash-licenses](https://github.com/eclipse/dash-licenses) and verifies, that our `DEPENDENCIES` files is up-to-date and does not contain any `restricted` or `rejected` dependencies.
Fixes #655

chore(ci): add dash workflow for PRs

---

community/open-meetings.mdx
static/meetings/committer-office-hour.ics
static/meetings/newjoiner-office-hour.ics
static/meetings/office-hour.ics
static/meetings/security-office-hour.ics

This PR adds four new meetings to our [open meetings](https://eclipse-tractusx.github.io/community/open-meetings) page.
All the four meetings are created in the same way. They provide a session link and downloadable ICS file for the calendar.
Everybody can bypass the lobby and the recording doesn't start automaticity.
**You are welcome to comment and suggest changes if needed. We are a little bit limited in formating the description :) but we can add more information to the ics file**
_Initially, the plan for the committer hours was every first and third Friday, but that's not possible to select :(_

doc(open meetings): add four open meetings

---

community/open-meetings.mdx
static/meetings/committer-office-hour.ics

This PR changes the committer meeting rotation from every third Friday to every two weeks.

doc(open meetings): change of the committer meeting rotation

---

.github/workflows/lint-on-pull-request.yaml
README.md
package.json

This PR enables the markdown linter for the KITs.
Fixes #673 

feat: enable markdown linter for kits

---

utils/coreOnboardingServices.js

operator page core and onboarding service section has wrong repo urls in the respective sections

fix(operator): update repo urls in the operator page

---

community/open-meetings.mdx
src/components/OpenMeetings/MeetingInfo.jsx

This PR adds the functionality to open meetings to publish also additional links, cause it is not possible in the description
e.g.

feat(open meetings): add functionality to add additional links

---

src/components/OpenMeetings/MeetingInfo.jsx

Currently, we can only link to the [open-meeting page](https://eclipse-tractusx.github.io/community/open-meetings) itself, but not to a specific meeting entry.
This PR adds the needed functionality to add id and anchor to each meeting.

feat(open meetings): add anchor to link to open meeting

---

docs/tutorials/e2e/inform/onboardingMaterial.md

Fixes that a link was surrounded by double `<<` and `>>`, which resulted in a broken link when rendered. 
Attribution goes to `sovity GmbH` (already covered) even though coming from a private fork.

fix: Syntax of a broken link

---

docs/release/trg-5/trg-5-01.md
docs/release/trg-5/trg-5-05.md

- Restructure **TRG501** and **TRG5.05**, most values file related info over
- Add examples and rules for chart values like ingress, dependencies, container

docs: restructure and update TRG 5.01 and 5.05

---

blog-meeting-minutes/2024-02-29-security-hour.md
blog-meeting-minutes/authors.yaml

Adding the security office hour meeting minutes for 2024-02-29.

docs(open-meetings): add 02-29 security office hour minutes

---

DEPENDENCIES
community/open-meetings.mdx

This PR fixes a date issue for the open meeting `Tractus-X Open Planning R24.08`. It also cleans up the [Onetime](https://eclipse-tractusx.github.io/community/open-meetings#one-time-meetings) because old meetings should be deleted. Additionally it adds the links for the meeting minutes.

fix(open meetings): cleanup open meetings

---

docs/release/trg-7/trg-7-01.md

- fix link within TRG 7-01 to 7.04 and 7.08
fixes https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/722

fix: link to trg 7-08

---

blog-meeting-minutes/2024-03-28-security-hour.md
blog-meeting-minutes/authors.yaml

Adding the security office hour meeting minutes for 2024-03-28.

docs: add security office hour meeting minutes 2024-03-28

---

blog-meeting-minutes/2024-04-05-office-hour.md

This is the meeting minutes for the office hour meeting on 05 april

docs(office-hour): add april 05 meeting minutes

---

community/open-meetings.mdx
static/meetings/committer-office-hour.ics
static/meetings/office-hour.ics
static/meetings/security-office-hour.ics

Since we switched to *summer time*, some downloaded meetings are moved for 1 hour. This PR adapts the related ICS files. The blockers are shown correctly now in the calendar.

fix(open meetings): change open meeting timezosnes to cest

---

blog/2024-04-10-open-planning-r24.08.mdx

This pr add the agenda and also a detailed one for the open planning for release 24.08

doc(news blog): agenda for open planning R24.08

---

docs/release/trg-6/trg-6-1.md

PR to update prerequisites of TRG-6.01 related to GitHub Chart Releaser Action as per https://github.com/helm/chart-releaser-action the `Source Branch` needs to be set to `gh-pages`.
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/444

docs: add requirement to TRG-6.01

---

blog/2024-04-10-open-planning-r24.08.mdx

Since we were unable to discuss all the features… this, Pr prepares the agenda for the second planning day

doc(open planning): adapt the agenda for open planning

---

docs-kits/kits/Connector Kit/Adoption View/adoption-view.md
docs-kits/kits/Connector Kit/Operation View/operation-view.md

Reading through the connector kit I found two typos which I fixed with this pull request

doc(conn): Fix two typos in connector kit

---

blog-meeting-minutes/2024-05-03-community-hour.md

Add the meeting minutes for may 03 2024

docs(meetings): add office hour meeting minutes for may 03

---

blog/2024-07-31-open-planning-r24.12.mdx
utils/newsTitles.js

This PR adds the new entry for our open planing for release 24.12. The agenda for each meeting is not included because it is dependent on the features on the Release Planning Board (GitHub).

doc(news blog): add news blog for open planning 24.12

---

documentation/kit-maturity-levels.md

In this pull request, we have successfully resolved the issue affecting the rendering of the table under the kit-maturity-level file. The table now displays as expected.
#880 

documentation(kit-maturity-levels):Issue has been fixed

---

DEPENDENCIES
docs-kits/kits/Traceability Kit/Software Development View/page_app-provider_software-development-view.mdx
docs-kits/kits/Traceability Kit/page_changelog.mdx

- Remove space before 'http' (linter?)
- Use 'Set' instead of 'Policy' because of EDC
- prefix UsagePurpose with according value namespace cx.core.*
- Remove version from cx-policy namespace
- Update FrameworkAgreement rightOperand with upper case credential name

Fix Traceability Policy example

---

docs-kits/kits/Traceability Kit/Software Development View/page_app-provider_software-development-view.mdx
docs-kits/kits/Traceability Kit/page_changelog.mdx

Instead of use case specific legal documents / credentials, there is now a single consolidated document and consquently also a single Verifiable Credential. Policies need to be updated accordingly.

Traceability: Upate to latest (2408) DataExchangeGovernance

---

docs/release/trg-0/trg-9-01.md

link to the respective sections maturity-level kits and artifacts from trg file fixed
Issue - #916 

fix: fixed link issue

---

docs-kits/kits/Connector Kit/Adoption View/policies-in-catena.md
docs-kits/kits/Connector Kit/Development View/specifications.md
docs-kits/kits/Connector Kit/page_changelog.md

Instead of use case specific legal documents / credentials, there is now a single consolidated document and consquently also a single Verifiable Credential. Policies need to be updated accordingly.

Connector: Upate to latest (2408) DataExchangeGovernance

---

docs-kits/kits/Digital Twin Kit/Software Development View/page_interaction-patterns.md
docs-kits/kits/Digital Twin Kit/Software Development View/page_software-development-view.md
docs-kits/kits/Digital Twin Kit/page_adoption-view.md
docs-kits/kits/Digital Twin Kit/page_changelog.md
docs-kits/kits/Digital Twin Kit/page_software-operation-view.md
docs-kits/kits/OSim Kit/Software Development View/02-page_software-development-view.md
docs-kits/kits/OSim Kit/page_adoption-view.md
docs-kits/kits/OSim Kit/page_changelog.md

Previously, the DT Kit's copyright notice contained incorrect links to source. OSim was missing some all along
Fixes #864 

chore: correct copyright notices

---

docusaurus.config.js
utils/kitsGallery.js

Resolves #914.
BUG: The link to the Behaviour Twin KIT (24.05) in the  KITs menue and in the KITs gallery were pointing to "next" version instead of 24.05 version. 
Resolved by removing "next/" from the link addresses.

Behaviour Twin KIT 24.05: Resolved Issue 914: Corrected links to Behaviour Twin KIT

---

DEPENDENCIES
documentation/kit-artifacts.md

In this pull request , we have fixed the broken link in kit artifacts file.

documentation(kit-artifacts):broken link has been fixed

---

blog-meeting-minutes/2024-06-21-community-hour.md
blog-meeting-minutes/authors.yaml

- Office hour meeting minutes from 21.06.2024

docs: added meeting minutes office hour 21.06.2024

---

docs/release/trg-5/trg-5-10.md

PR to bump current aligned kubernetes version in the [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10)

docs(trg): bump k8s version

---

blog-meeting-minutes/2024-06-28-community-hour.md
blog-meeting-minutes/authors.yaml

add minutes for office hour from June 28, 2024

docs: add minutes for office hour from June 28, 2024

---

blog/2024-07-31-open-planning-r24.12.mdx
community/open-meetings.mdx

Since the appointment cannot take place, this PR marks it as cancelled. 
It's by purpose marked as cancelled and not deleted.

doc(release planning): cancel refinement day 1 in release planning 24.12

---

blog-meeting-minutes/2024-06-20-security-hour.md

Adding the security office hour meeting minutes for 2024-06-20.

docs: security office hour meeting minutes 2024-06-20

---

blog-meeting-minutes/2024-07-05-community-hour.md

add minutes for office hour from 05-July 2024

docs: add meeting minutes for office hour from 05-July 2024

---

docs/release/trg-0/trg-4-08.md
docs/release/trg-4/trg-4-01.md
docs/release/trg-4/trg-4-05.md
docs/release/trg-4/trg-4-08.md

- add TRG for multi-platform (amd64 and arm64) builds of container images
this is especially beneficial for supporting use cases like tutorials and local playgrounds
- also, consolidate to one example workflow for TRG-4 section

chore(trg-4.08): add draft for multi-platform builds

---

docs/release/trg-0/trg-1-09.md
docs/release/trg-9/_category_.json
docs/release/trg-9/trg-9-01.md

docs: add TRG for UX/UI styleguide

---

docs-kits/kits/Eco_Pass_KIT/page-adoption-view.md

There was missing the DPP Tutorial to be linked to the KIT. It was presented in the Second Tractus-X Community Days and it is really valuable for easing the adoption of the KIT.
I also added the dpp-verification documentation so that people can easily read more about the concept in the Digital Product Pass Verification Add-on Section.

chore(ecopass-kit): added dpp-tutorial  & dpp-verification to the KIT adoption view

---

community/open-meetings.mdx

Removed meeting which was exceeded by the 26.6.2024

Remove exceeded-tractus-x-meeting ending on 26.6.2024

---

community/open-meetings.mdx

The open meeting for Security - Office Hour will be discontinued due to lack of security experts post consortia.
The meeting was hosted by @RoKrish14, every 2 weeks on Thursday from 08:35 am to 09:30 am CEST.
The[meeting minutes](https://eclipse-tractusx.github.io/community/meeting-minutes) of the previous office hour can still be found under open meetings page.

doc(open meetings): removed open meeting for secuirty meeting hour

---

docs-kits/kits/Eco_Pass_KIT/changelog.md

We need to generate a proper changelog for this R24.08.
This is the changelog: 
- Added Digital Product Pass Verification Section in adoption view
- Added Digital Product Pass Tutorial Section adoption view & software view
- Added Digital Product Passport as Enabler for Circular Economy Whitepaper reference
- Updated DPP model to version v5.0.0
- Updated BatteryPass to v6.0.0
- Updated TransmissionPass to v3.0.0
- Updated DPP Verification add-on in the software development view.

chore(ecopass-kit): added R24.08 changelog for the ecopass-kit

---

blog-meeting-minutes/2024-07-26-community-hour.md
blog-meeting-minutes/authors.yaml

Added the office hour meeting minutes for 26.07.2024 meeting.

chore: added community hour meeting minutes 26.07.2024

---

docs-kits_versioned_sidebars/version-24.05-sidebars.json
docusaurus.config.js
sidebarsDocsKits.js

remove upcoming kits from next and 24.05.
add data governance kit in the nav bar
#921 

fix: remove upcoming kits  add data governance kit

---

utils/kitsGallery.js

Fix DCM links due to structural changes
Please describe your PR: 
- What does this PR introduce? Fix correct link to DCM landing page in Eclipse Tractus-X
- Does it fix a bug? No
- Does it add a new feature? No
- Is it enhancing documentation? No
#1018 

Fix DCM links due to structural changes

---

docs/release/trg-8/trg-8-03.md

This PR introduces TruffleHog as a new open source tool for secret scanning to be used alongside native Github Secret scanning. This is being enforced as a replacement to the existing GitGuardian (commercial) tool.
Example workflow:
1. https://github.com/eclipse-tractusx/bpdm/blob/main/.github/workflows/trufflehog.yml
2. https://github.com/eclipse-tractusx/demand-capacity-mgmt/blob/main/.github/workflows/trufflehog.yml
Please note: The TRG checks continues for 24.08 under GitGuardian for secret scanning.
The teams who have already implemented TruffleHog, can also be considered for the TRG checks.
**NOTE: Please do not merge this PR until the August release**

docs: update trg-8-03.md, introduce TruffleHog 

---

docs-kits/kits/knowledge-agents/development-view/modules.md
docs-kits/kits/knowledge-agents/development-view/reference.md
docs-kits/kits/knowledge-agents/operation-view/agent_edc.md
docs-kits/kits/knowledge-agents/operation-view/bridge.md
docs-kits/kits/knowledge-agents/operation-view/deployment.md
docs-kits/kits/knowledge-agents/operation-view/ka_conformity_scripts.postman_collection.json
docs-kits/kits/knowledge-agents/operation-view/policy.md
docs-kits/kits/knowledge-agents/operation-view/provider.md
docs-kits/kits/knowledge-agents/operation-view/testbed.md
docs-kits/kits/knowledge-agents/page_changelog.md

Updates Knowledge Agents Kit to the CX 24.08 Release.
Especially cares about including the AAS Bridge Release.

docs: Knowledge Agents for CX 24.08 

---

docs/release/trg-4/trg-4-02.md

PR to fix/replace .tractusx metadata file url (linking to archived repo) in the TRG 4.02.

doc(trg): replace link to metadata file doc

---

community/open-meetings.mdx
static/meetings/refinement-day-1---release-2503.ics
static/meetings/refinement-day-2---release-2503.ics

Unfortunately, we have to reschedule the meetings for the Refinement Day 1 and 2. Both were on Mondays, which is not perfect. With this PR, both are moved for two Days to Wednesday.

fix(open-meetings): adapt the dates for open meetings

---

blog/2024-10-16-refinement-day-1-R24.03.mdx
utils/newsTitles.js

This PR add a new entry in our Blog section to announce and provide some guidance for refinement day 1.

docs(news blog): add new blog entry for refinement day 1 in R25.03

---

blog/2024-10-16-refinement-day-1-R25.03.mdx
blog/2024-11-06-refinement-day-2-R25.03.mdx
utils/newsTitles.js

This PR fixes some naming issues within refinement day 1 and adds a new entry for refinement day 2

docs(news-blog): add new entry for refinement day 2

---

community/open-meetings.mdx

This PR adds more information to our meetings, e.g. the link to the timeline and also a link to our talkboard. 
Thanks, @ma3u, for bringing this up

docs(open-meetings): add timelines and taskboards to open meetings

---

community/open-meetings.mdx

Just a short fix ... there is one word obsolete ;)

doc(open meetings): fix wording in open meeting

---

blog/2024-11-13-open-planning-R25.03.mdx
utils/newsTitles.js

This PR adds more information to the planned open planning meeting. The information is provided via news blog, which looks like:

docs(news-blog): add news blog for open planning

---

src/pages/release-information.md

This PR adds the information about the timelines, which are available on the Release Planning Board.
Closes #1012 

docs(releaseinformation): add a tip admonition to mention the timelines

---

blog/2024-11-13-open-planning-R25.03.mdx
community/open-meetings.mdx

This PR adds a detailed agenda to the open planning news blog and fixes some broken links in the open meetings section.

docs(open planning): adapt open meetings and open planning

---

blog/2024-11-06-tx-edc-bugfix.md

Provide a blog post to announce bugfix release 0.7.7 of Eclipse Tractus-X EDC

Add blog post for EDC 0.7.7 release

---

DEPENDENCIES
docs-kits/kits/Digital Twin Kit/Software Development View/page_interaction-patterns.md

In the EDC context, the data consumer does not bypass the EDC so fetch the data from the submodel server. That would mean that the submodel server is reachable via public internet. The standard dictates that the dataflow happens via the EDC. Also, in the previous diagram is described, that the digital twin in the submodel server is registered as an asset in the EDC. Why doing that, if the EDC is bypassed and the asset never consumed?

Updated digital twin consumption sequence diagram

---

DEPENDENCIES
docs/release/trg-7/trg-7-09.md

Proposed a TRG for product deprecation including a process and criteria to close #1037 
I didn't create a draft as I don't want to create two PRs following non-merged process within this [PR](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/871/files#diff-3210ef63113a43f664e14902d9cb192b6b77c3a7ac66b8b736db460fc7a5f14a).

docs: proposed TRG 7.09 for repository deprecation

---

src/pages/release-information.md

This PR adds more information about our releases, including phases, milestones, and timelines. The idea is not to provide the information redundant to the working model, but to provide a minimal set of information.

docs(release information): add more information to our release description

---

sidebarsDocsKits.js

This pull request updates development view for business partner kit where swagger api documentation links are updated.
The swagger documentation for all services in BPDM app version 6.2.0 is now linked to business partner kit.

[Business Partner Kit 24.12]: update api doc link to bpdm app version 6.2.0

---

docs/release/trg-7/trg-7-01.md
docs/release/trg-7/trg-7-04.md

Modify TRG 7.04 to describe how the DEPENDENCIES file could be not checked in the git repository but uploaded on a static content.
As discussed in: https://github.com/orgs/eclipse-tractusx/projects/61/views/6?pane=issue&itemId=83404189

docs: update TRG 7-04 to unbind DEPENDENCIES file from the main branch

---

community/open-meetings.mdx

This pull request just adjusts the timing for BPDM - Open Meeting.
`Every Wednesday effective 4. Dec 2024 until 28. May 2025 from 09:45 am to 10:15 am CET`

doc(open-meeting): adjusted open meeting for bpdm

---

.github/workflows/trufflehog.yml
docs/release/trg-8/trg-8-03.md

The Trufflehog workflow shall be updated to the latest configuration proposed by  @RoKrish14. 
Now the `--only-verified` is required so that the false positives are not appearing often.

chore: updated trufflehog workflow,  added missing flags

---

blog/2025-02-19-release-planning-R25.06.mdx
community/open-meetings.mdx
utils/newsTitles.js

This pull request introduces updates to the release planning documentation and related community meeting information for the upcoming Eclipse Tractus-X Release 25.06.
- Updates to Release Planning Documentation
- Updates to Community Open Meetings
- Updates to News Titles

docs(release-planning): add needed information for release planning 25.06

---

blog/2025-02-19-release-planning-R25.06.mdx

This pull request aims to improve clarity and structure for the Eclipse Tractus-X Release R25.06 planning sessions.

docs(open meetings): delete redundante content

---

community/open-meetings.mdx

**This PR should be merged until the end of the year 2024**
It adapts the concrete timeslot for the office hour and extends office hour and committer hour to 2025

docs(open-meetings): update office hour and extend meetings for 2025

---

DEPENDENCIES
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/development-view/modules.md
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/development-view/reference.md
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/operation-view/agent_edc.md
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/operation-view/bridge.md
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/operation-view/deployment.md
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/operation-view/ka_conformity_scripts.postman_collection.json
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/operation-view/policy.md
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/operation-view/provider.md
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/operation-view/testbed.md
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/page_changelog.md

Companion PR to https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1006 in order to sync the versioned folder of the knowledge agents kit 24.08 with its main version.
DEPs are outdated already in the main branch. Did not do any changes to the modules.

fix: backport knowledge-agents 24.08 changes to versioned folder.

---

DEPENDENCIES
docs/release/trg-9/_category_.json

This PR fixes a typo in the headline
Fixes #1100 

fix(trg9): typo in headline

---

docs/release/trg-5/trg-5-02.md

This PR replaces one "small" reference to Catena-X NG, since we would like to archive the  Catena-X NG GitHub ORG as soon as possible.
This PR adds value to #1026 

docs: delete reference to catena-x ng

---

DEPENDENCIES
blog/2025-05-22-fourth-community-days.mdx
utils/newsTitles.js

This PR adds a news BLOG for our fourth Eclipse Tractus-X Community Days and looks like

docs(news-blog): add blog for fourth Eclipse Tractus-x Community Days

---

DEPENDENCIES
docs-kits/kits/knowledge-agents/development-view/api.md
docs-kits/kits/knowledge-agents/development-view/modules.md
docs-kits/kits/knowledge-agents/operation-view/ka_conformity_scripts.postman_collection.json

Removed remaining references to catenax-ng from the agents kit.

fix: remove last references to catenax-ng artifacts from ka kit

---

community/open-meetings.mdx

As defined in this design decision: https://github.com/eclipse-tractusx/industry-core-hub/blob/main/docs/architecture/decision-records/0002-tractus-x-sdk.md
The industry core hub will in parallel develop in another repository a reusable tool box for the EDC, DTR and the Submodel Server.

chore: added tractusx-sdk to open meetings

---

docs-kits/kits/Connector Kit/Adoption View/adoption-view.md

fix: typos

---

docs/release/trg-5/trg-5-02.md

Replaced link to the apache license with one that does not point to a catenax-ng Repo, but to apache instead.

Replaced link to catenax-ng

---

docs-kits/kits/Connector Kit/Adoption View/adoption-view.md
docs-kits_versioned_docs/version-24.08/kits/Connector Kit/Adoption View/adoption-view.md
docs-kits_versioned_docs/version-24.12/kits/Connector Kit/Adoption View/adoption-view.md
utils/kitsGallery.js

This PR fixes some broken links to DCM Kit. After the KIT was renamed, the links didn't work any more.

fix(broken links): after renaming dcm KIT

---

docs-kits/kits/logistics-kit/adoption-view.md

A minor typo leads to a broken link in the new Logistics KIT Adoption View at https://eclipse-tractusx.github.io/docs-kits/kits/logistics-kit/adoption-view in Section "Packing List".
Link target was intended for https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.packing_list/1.0.0/PackingList.ttl

Update Logistics KIT adoption-view.md - Typo for broken link

---

docs/oss/tooling.md

This PR adds a new page on our Eclipse Tractus-X webpage. It lists a list (right now only one) of recommended tools for our open-source development.
closes https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/1183

docs(oss tooling): add new tooling section in oss

---

blog/2025-05-22-fourth-community-days.mdx

Add agenda for the news page "Join us in May 2025 for the Fourth Eclipse Tractus-X Community Days!"

docs(news-blog): add agenda for fourth Eclipse Tractus-x Community Days

---

docs/release/trg-7/trg-7-09.md

Add step for security checks for reactivation of repositories.
This is needed because security checks are deactivated after 60 days of no changes.
Closes https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/1184

add step to activate security check

---

docs-kits/kits/knowledge-agents/changelog.md
docs-kits_versioned_docs/version-24.08/kits/knowledge-agents/changelog.md
docs-kits_versioned_docs/version-24.12/kits/knowledge-agents/changelog.md
docs-kits_versioned_docs/version-25.03/kits/knowledge-agents/changelog.md
docs-kits_versioned_sidebars/version-24.08-sidebars.json
docs-kits_versioned_sidebars/version-24.12-sidebars.json
docs-kits_versioned_sidebars/version-25.03-sidebars.json
sidebarsDocsKits.js

The ID of the changelog from the knowledge agents kit has been overlooked during the upgrade. This PR fixes the ID.

Chore(knowledge-agents): Fix wrong ID of Changelog

---

docs-kits/kits/eco-pass-kit/success-stories/battery-pass-viewer-app.mdx
docs-kits/kits/environmental-and-social-standards-kit/changelog.md
docs-kits/kits/environmental-and-social-standards-kit/documentation.md
docs-kits/kits/modular-production-kit/adoption-view.md
docs-kits/kits/modular-production-kit/changelog.md
docs-kits/kits/modular-production-kit/software-development-view/software-development-view.md
docs-kits/kits/supply-chain-disruption-notification-kit/changelog.md
docs-kits_versioned_docs/version-24.08/kits/eco-pass-kit/success-stories/battery-pass-viewer-app.mdx
docs-kits_versioned_docs/version-24.08/kits/environmental-and-social-standards-kit/changelog.md
docs-kits_versioned_docs/version-24.08/kits/environmental-and-social-standards-kit/documentation.md
docs-kits_versioned_docs/version-24.08/kits/modular-production-kit/adoption-view.md
docs-kits_versioned_docs/version-24.08/kits/modular-production-kit/changelog.md
docs-kits_versioned_docs/version-24.08/kits/modular-production-kit/software-development-view/software-development-view.md
docs-kits_versioned_docs/version-24.08/kits/supply-chain-disruption-notification-kit/changelog.md
docs-kits_versioned_docs/version-24.12/kits/eco-pass-kit/success-stories/battery-pass-viewer-app.mdx
docs-kits_versioned_docs/version-24.12/kits/environmental-and-social-standards-kit/changelog.md
docs-kits_versioned_docs/version-24.12/kits/environmental-and-social-standards-kit/documentation.md
docs-kits_versioned_docs/version-24.12/kits/modular-production-kit/adoption-view.md
docs-kits_versioned_docs/version-24.12/kits/modular-production-kit/changelog.md
docs-kits_versioned_docs/version-24.12/kits/modular-production-kit/software-development-view/software-development-view.md
docs-kits_versioned_docs/version-24.12/kits/supply-chain-disruption-notification-kit/changelog.md
docs-kits_versioned_docs/version-25.03/kits/eco-pass-kit/success-stories/battery-pass-viewer-app.mdx
docs-kits_versioned_docs/version-25.03/kits/environmental-and-social-standards-kit/changelog.md
docs-kits_versioned_docs/version-25.03/kits/environmental-and-social-standards-kit/documentation.md
docs-kits_versioned_docs/version-25.03/kits/modular-production-kit/adoption-view.md
docs-kits_versioned_docs/version-25.03/kits/modular-production-kit/changelog.md
docs-kits_versioned_docs/version-25.03/kits/modular-production-kit/software-development-view/software-development-view.md
docs-kits_versioned_docs/version-25.03/kits/supply-chain-disruption-notification-kit/changelog.md

Next to some last wrong IDs within the KITs I found and fixed an issue where the Modular Pruduction KIT Icon has been embedded incorrectly.

Chores: Fixed last missed IDs in KITs

---

blog/2025-03-20-release-planning-R25.09.mdx

Since the Refinement Day 1 and 2 have been removed and replaced by the Alignment Day, the Tractus-X page had to be adapted

Adapt alignment day

---

blog/2025-03-20-release-planning-R25.09.mdx

This pull request updates the agenda for the release planning day R25.09. The changes improve clarity and usability by refining the session descriptions and adding links to feature details for each topic.

docs(open planning): add detailed agenda

---

.github/workflows/dash.yaml

As discussed in today's office hour, this action should only be triggered, if there is a change (This would probably mean, new libs are introduced and need to be checked.) on package-lock.json -> This reduces waiting time and resources on the Eclipse side/dash side

feat(dash-action): adapt to be executed only on change

---

blog-meeting-minutes/2025-04-25-community-hour.md
blog-meeting-minutes/authors.yaml

* add meeting minutes for the meeting from 25.04.25
* add phil91 to authors

docs: add meeting minutes for 25th april

---

src/components/AboutUsCard/styles.module.css
src/components/NewsTicker/styles.module.css

news section description overriding with other content issue resolved. show full length text on about us card in home page
#1267 

fix: mobile browser style in home page

---

utils/products.js

Our product list is not up-to-date. This PR should help to clean it up. Two archived products were deleted, and the order was fixed. 
In the end, we should have a clean list of the Tractus-X products (real products) ⇾ including a list (for each product) of ACTIVE committer (who feel responsible for this specific product)
This is important for Release management and also for Test management
What is needed from @eclipse-tractusx/automotive-tractusx-committers 
Expected result, after PR is merged ⇾ clear overview about the products/committers ⇾ is there any product without a committer?
Productlist -> checked and up-to-date??

docs(product-list): cleanup product list

---

community/open-meetings.mdx

I have added a new section for the "general" office hours in the topic, and added the product office hours below.

chore: added new office hour structure + removed hours from ICHUB

---

community/open-meetings.mdx

The identity hub got a new matrix chat, weekly meeting and planning board.
Also removed the CET from the times, since it is defined in the beginning already

chore: added identity hub weekly & removed CET

---

utils/carouselCommunityInfo.js

This PR just renames the `DevHub` section into `Developer Hub`, cause thats the name we use everywhere else.
Small CleanUp

fix(naming consistency): rename DevHub -> Developer Hub

---

docs-kits_versioned_sidebars/version-25.06-sidebars.json
sidebarsDocsKits.js

- The next version of the KIT and the 25.06 hold a wrong IRS API version. It should be 7.0.1.

chore: update correct version of irs api for 25.06 and NEXT data chain kits

---

docs/release/trg-0/trg-0.md

As already discussed in the office hour, the change log is not needed (redundant) -> this PR deletes the overall TRG changelog

chore(trg-change-log): delete TRG change log

---

docs-kits/kits/business-partner-kit/adoption-view.md
docs-kits/kits/business-partner-kit/changelog.md
docs-kits/kits/business-partner-kit/documentation-bpdm/bpdm-arc42.md
sidebarsDocsKits.js

This pull request adds business partner kit update based on latest bpdm application version 7.1.0.
The changes performed are as below -
- Updated change log to 10.0.0 for business partner kit
- Updated latest version api-hub link to development view for business partner kit.
- Updated adoption view with correct link for Business Partner Use Case and Catena-X Standard Library.
- Updated architecture document.
Contributes to https://github.com/eclipse-tractusx/bpdm/issues/1413 and https://github.com/eclipse-tractusx/sig-release/issues/1487

[Business Partner KIT] Release 25.09

---

community/open-meetings.mdx

This pull request adjusts the teams meeting link and details for BPDM - Open Meeting.
Every Wednesday from 10:00 am to 10:30 am
Contributes to https://github.com/eclipse-tractusx/bpdm/issues/1436

doc(open-meeting): adjusted open meeting teams link for bpdm

---

.tractusx
docs-kits/kits/product-carbon-footprint-exchange-kit/software-development-view.md
openApi/pcf/kit_pcf-openAPI_1-1-2.yaml

This PR add the new API version 1.1.2 to the KIT itself and also to the API Hub. The related yaml file was taken (as discussed) from this [source](https://github.com/catenax-eV/product-standardization-prod/blob/8ac803075b78db3f3a74b0c0d9b8edb3f93d3d3e/standards/CX-0136-UseCasePCF/assets/catena-x-pcf-endpoint-1_1_2.yaml) -> closed repository, since it was developed there.

docs(pcf-exchange-kit): add new api version to KIT and API-HUB
